[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "fec"
author = "Tom Augspurger"
author-email = "tom.augspurger88@gmail.com"
home-page = "tomaugspurger.github.com"
classifiers = ["License :: OSI Approved :: MIT License"]

